# Generated by Django 4.2.6 on 2023-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_18',
            field=models.BooleanField(default=True, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_registration',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
